/// Flutter icons MyIconsCovid
/// Copyright (C) 2020 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  MyIconsCovid
///      fonts:
///       - asset: fonts/MyIconsCovid.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class MyIconsCovid {
  MyIconsCovid._();

  static const _kFontFam = 'MyIconsCovid';
  static const _kFontPkg = null;

  static const IconData icon_pdp = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData icon_konfirm = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData icon_odp = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
